### ISSUE TITLE
Consider merging into debug?

### ISSUE THREAD

**Issue by ndmitchell** [pepeiborra/debug-hoed#1]
There are legitimate reasons to use both `debug` and `debug-hoed` (requiring `Observable` vs not working with laziness), and those reasons will never go away. If you wanted to move `debug-hoed` into `debug`, we could rename `Debug` the module to `Debug.Hoed` and `Debug.Variables` (or a better name...) and let people switch between the possible modes more easily.

Thoughts?

**Comment by ndmitchell** [comment]
If you did want to merge, I would suggest giving you commit rights to debug, since a large chunk of the code would be mostly yours.

**Comment by pepeiborra** [comment]
I don’t see any problem with that, provided that debug-hoed works as advertised. Nested observations are not what Hoed was designed for, and @MaartenFaddegon and myself are still reviewing the changes.

**Comment by pepeiborra** [comment]
I have identified the problem with nested observations in Hoed and sent @MaartenFaddegon [a fix](https://github.com/MaartenFaddegon/Hoed/pull/12). This is the only obstacle (as far as I know) to continuing the work on debug-hoed.

**Comment by pepeiborra** [comment]
@MaartenFaddegon has made a release of Hoed with the fix for nested observations and performance improvements, so I'm thinking of merging debug-hoed to debug today.

**Comment by ndmitchell** [comment]
Sounds good.

**Comment by pepeiborra** [comment]
Done !
